// fixtures/openslides/svelte/src/shared/ui/Button.svelte
<script lang="ts" module>
  import { cva, type VariantProps } from "class-variance-authority";
  import type { Snippet } from "svelte";
  import type { HTMLButtonAttributes } from "svelte/elements";

  export const buttonVariants = cva(
    "inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:size-4 [&_svg]:shrink-0",
    {
      variants: {
        variant: {
          default: "bg-primary text-primary-foreground hover:bg-primary/90",
          destructive:
            "bg-destructive text-destructive-foreground hover:bg-destructive/90",
          outline:
            "border border-input bg-background hover:bg-accent hover:text-accent-foreground",
          secondary:
            "bg-secondary text-secondary-foreground hover:bg-secondary/80",
          ghost: "hover:bg-accent hover:text-accent-foreground",
          link: "text-primary underline-offset-4 hover:underline",
        },
        size: {
          default: "h-9 px-4 py-2",
          sm: "h-8 rounded-md px-3 text-xs",
          lg: "h-10 rounded-md px-6",
          icon: "h-8 w-8",
        },
      },
      defaultVariants: {
        variant: "default",
        size: "default",
      },
    },
  );

  export interface ButtonProps extends HTMLButtonAttributes {
    variant?: VariantProps<typeof buttonVariants>["variant"];
    size?: VariantProps<typeof buttonVariants>["size"];
    class?: string;
    children?: Snippet;
    ref?: HTMLButtonElement | null;
  }
</script>

<script lang="ts">
  import { cn } from "$lib/lib/utils";

  let {
    variant = "default",
    size = "default",
    class: className = undefined,
    type = "button",
    children,
    ref = $bindable(null),
    ...rest
  }: ButtonProps = $props();
</script>

<button
  bind:this={ref}
  {type}
  class={cn(buttonVariants({ variant, size, className }))}
  {...rest}
>
  {@render children?.()}
</button>

// fixtures/openslides/vue/src/shared/ui/Button.vue
<script setup lang="ts">
import { computed, ref, useAttrs } from "vue";
import { cva, type VariantProps } from "class-variance-authority";
import { cn } from "$lib/lib/utils";

const buttonVariants = cva(
  "inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:size-4 [&_svg]:shrink-0",
  {
    variants: {
      variant: {
        default: "bg-primary text-primary-foreground hover:bg-primary/90",
        destructive:
          "bg-destructive text-destructive-foreground hover:bg-destructive/90",
        outline:
          "border border-input bg-background hover:bg-accent hover:text-accent-foreground",
        secondary:
          "bg-secondary text-secondary-foreground hover:bg-secondary/80",
        ghost: "hover:bg-accent hover:text-accent-foreground",
        link: "text-primary underline-offset-4 hover:underline",
      },
      size: {
        default: "h-9 px-4 py-2",
        sm: "h-8 rounded-md px-3 text-xs",
        lg: "h-10 rounded-md px-6",
        icon: "h-8 w-8",
      },
    },
    defaultVariants: { variant: "default", size: "default" },
  },
);

type ButtonVariant = VariantProps<typeof buttonVariants>["variant"];
type ButtonSize = VariantProps<typeof buttonVariants>["size"];

const props = withDefaults(
  defineProps<{
    variant?: ButtonVariant;
    size?: ButtonSize;
    type?: "button" | "submit" | "reset";
  }>(),
  {
    variant: "default",
    size: "default",
    type: "button",
  },
);

const attrs = useAttrs();
const element = ref<HTMLButtonElement | null>(null);
const classes = computed(() =>
  cn(
    buttonVariants({ variant: props.variant, size: props.size }),
    attrs.class as string | undefined,
  ),
);

defineExpose({
  focus: () => element.value?.focus(),
});
</script>

<template>
  <button ref="element" v-bind="$attrs" :type="type" :class="classes">
    <slot />
  </button>
</template>
