// fixtures/openslides/svelte/src/shared/ui/CodeThumbnail.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import { cn } from "$lib/lib/utils";
  import { themeBackground } from "$lib/types";

  let {
    html,
    fallback = null,
    theme,
    fontSize = 5.5,
    lineHeight = 1.35,
    class: className,
    codeClassName,
    ref = $bindable(null),
    style,
  }: {
    html: string | null;
    fallback?: Snippet | null;
    theme: string;
    fontSize?: number;
    lineHeight?: number;
    class?: string;
    codeClassName?: string;
    ref?: HTMLDivElement | null;
    style?: string;
  } = $props();
</script>

<div
  bind:this={ref}
  class={cn("relative w-full overflow-hidden", className)}
  style="background-color: {themeBackground(theme)};{style ?? ''}"
  aria-hidden="true"
>
  {#if html}
    <code
      class={cn(
        "pointer-events-none block overflow-hidden font-mono",
        codeClassName,
      )}
      style="font-size: {fontSize}px; line-height: {lineHeight}; white-space: pre;"
      >{@html html}</code
    >
  {:else if fallback}
    {@render fallback()}
  {/if}
</div>

// fixtures/openslides/vue/src/shared/ui/CodeThumbnail.vue
<script setup lang="ts">
import { themeBackground } from "$lib/lib/themes";
import { cn } from "$lib/lib/utils";

withDefaults(
  defineProps<{
    html: string | null;
    theme: string;
    fontSize?: number;
    lineHeight?: number;
    class?: string;
    codeClassName?: string;
  }>(),
  {
    fontSize: 5.5,
    lineHeight: 1.35,
    class: undefined,
    codeClassName: undefined,
  },
);
</script>

<template>
  <div
    :class="cn('relative w-full overflow-hidden', $props.class)"
    :style="{ backgroundColor: themeBackground(theme) }"
    aria-hidden="true"
  >
    <code
      v-if="html"
      :class="
        cn(
          'pointer-events-none block overflow-hidden font-mono',
          codeClassName,
        )
      "
      :style="{
        fontSize: `${fontSize}px`,
        lineHeight,
        whiteSpace: 'pre',
      }"
      v-html="html"
    />
    <slot v-else name="fallback" />
  </div>
</template>
