// fixtures/openslides/vue/src/features/settings/SettingsDrawer.vue
<script setup lang="ts">
import { computed } from "vue";
import { X } from "lucide-vue-next";
import type { Project, ProjectSettings } from "$lib/types";
import { availableThemes } from "$lib/lib/themes";
import Button from "$lib/ui/Button.vue";
import SliderField from "$lib/ui/SliderField.vue";
import Switch from "$lib/ui/Switch.vue";
import { backendConfig } from "$lib/lib/backend-config";
import {
  setEditorShowLineNumbers,
  setShowSlideHoverPreview,
  ui,
} from "$lib/stores/ui-state";

const props = defineProps<{ open: boolean; project: Project }>();
const emit = defineEmits<{
  close: [];
  settings: [patch: Partial<ProjectSettings>];
  theme: [theme: string];
}>();
const settings = computed(() => props.project.settings);
const themes = availableThemes();
</script>

<template>
  <Transition name="drawer">
    <aside
      v-if="open"
      class="fixed inset-y-0 right-0 z-50 w-[360px] overflow-y-auto border-l border-border bg-card shadow-2xl"
      role="dialog"
      aria-label="Settings"
    >
      <header
        class="sticky top-0 z-10 flex h-12 items-center justify-between border-b bg-card/95 px-4 backdrop-blur"
      >
        <h2 class="text-sm font-semibold">Presentation settings</h2>
        <Button
          variant="ghost"
          size="icon"
          aria-label="Close settings"
          @click="emit('close')"
        >
          <X />
        </Button>
      </header>
      <div class="space-y-7 p-4">
        <section class="space-y-3">
          <h3 class="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
            Theme
          </h3>
          <div class="grid grid-cols-4 gap-2">
            <button
              v-for="theme in themes"
              :key="theme.value"
              class="aspect-square rounded-lg border transition-transform hover:scale-105"
              :class="
                project.theme === theme.value
                  ? 'ring-2 ring-primary ring-offset-2 ring-offset-card'
                  : ''
              "
              :style="{ backgroundColor: theme.background }"
              :title="theme.label"
              @click="emit('theme', theme.value)"
            />
          </div>
        </section>
        <section class="space-y-4">
          <h3 class="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
            Preview
          </h3>
          <SliderField
            label="Preview font"
            :value="settings.fontSize"
            :min="10"
            :max="72"
            :step="1"
            :format="(value) => `${value}px`"
            @commit="emit('settings', { fontSize: $event })"
          />
          <SliderField
            label="Line height"
            :value="settings.lineHeight"
            :min="1"
            :max="2.4"
            :step="0.05"
            :format="(value) => value.toFixed(2)"
            @commit="emit('settings', { lineHeight: $event })"
          />
          <SliderField
            label="Editor font"
            :value="settings.editorFontSize"
            :min="10"
            :max="32"
            :step="1"
            :format="(value) => `${value}px`"
            @commit="emit('settings', { editorFontSize: $event })"
          />
          <label class="flex items-center justify-between gap-4 text-xs">
            Editor line numbers
            <Switch
              :model-value="ui.editorShowLineNumbers"
              @update:model-value="setEditorShowLineNumbers"
            />
          </label>
          <label class="flex items-center justify-between gap-4 text-xs">
            Slide hover previews
            <Switch
              :model-value="ui.showSlideHoverPreview"
              @update:model-value="setShowSlideHoverPreview"
            />
          </label>
          <label class="block space-y-1.5 text-xs">
            <span class="text-muted-foreground">Language</span>
            <select
              :value="settings.language"
              class="h-8 w-full rounded-md border border-input bg-background px-2 text-xs"
              @change="
                emit('settings', {
                  language: ($event.currentTarget as HTMLSelectElement).value,
                })
              "
            >
              <option
                v-for="language in backendConfig.languages"
                :key="language.value"
                :value="language.value"
              >
                {{ language.label }}
              </option>
            </select>
          </label>
          <div class="grid grid-cols-2 gap-2" role="radiogroup" aria-label="Code alignment">
            <button
              v-for="alignment in ['left', 'center'] as const"
              :key="alignment"
              class="rounded-md border px-3 py-2 text-xs capitalize"
              :class="
                settings.codeAlign === alignment
                  ? 'border-primary bg-primary/10 text-primary'
                  : 'border-input'
              "
              @click="emit('settings', { codeAlign: alignment })"
            >
              {{ alignment }}
            </button>
          </div>
          <label class="flex items-center justify-between gap-4 text-xs">
            Show line numbers
            <Switch
              :model-value="settings.showLineNumbers"
              @update:model-value="
                emit('settings', { showLineNumbers: $event })
              "
            />
          </label>
          <label class="flex items-center justify-between gap-4 text-xs">
            Pure black code background
            <Switch
              :model-value="settings.useBlackCodeBackground"
              @update:model-value="
                emit('settings', { useBlackCodeBackground: $event })
              "
            />
          </label>
          <label class="flex items-center justify-between gap-4 text-xs">
            Highlight step indicator
            <Switch
              :model-value="settings.showHighlightStepIndicator"
              @update:model-value="
                emit('settings', { showHighlightStepIndicator: $event })
              "
            />
          </label>
        </section>
        <section class="space-y-4">
          <h3 class="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
            Motion
          </h3>
          <SliderField
            label="Global transition"
            :value="settings.globalTransitionDuration"
            :min="0"
            :max="2000"
            :step="50"
            :format="(value) => `${value}ms`"
            @commit="
              emit('settings', { globalTransitionDuration: $event })
            "
          />
          <label class="flex items-center justify-between gap-4 text-xs">
            Use global transition
            <Switch
              :model-value="settings.useGlobalTransition"
              @update:model-value="
                emit('settings', { useGlobalTransition: $event })
              "
            />
          </label>
          <label class="flex items-center justify-between gap-4 text-xs">
            Use global stagger
            <Switch
              :model-value="settings.useGlobalStagger"
              @update:model-value="
                emit('settings', { useGlobalStagger: $event })
              "
            />
          </label>
          <label class="flex items-center justify-between gap-4 text-xs">
            Use global highlight settings
            <Switch
              :model-value="settings.useGlobalHighlight"
              @update:model-value="
                emit('settings', { useGlobalHighlight: $event })
              "
            />
          </label>
          <SliderField
            label="Global stagger"
            :value="settings.globalStagger"
            :min="0"
            :max="30"
            :step="1"
            @commit="emit('settings', { globalStagger: $event })"
          />
          <SliderField
            label="Highlight scale"
            :value="settings.globalSizeUpAmount"
            :min="100"
            :max="175"
            :step="1"
            :format="(value) => `${value}%`"
            @commit="emit('settings', { globalSizeUpAmount: $event })"
          />
          <div class="grid grid-cols-2 gap-2" role="radiogroup" aria-label="Highlight dim color">
            <button
              v-for="color in ['theme', 'black'] as const"
              :key="color"
              class="rounded-md border px-3 py-2 text-xs capitalize"
              :class="
                settings.highlightDimColor === color
                  ? 'border-primary bg-primary/10 text-primary'
                  : 'border-input'
              "
              @click="emit('settings', { highlightDimColor: color })"
            >
              {{ color }}
            </button>
          </div>
          <SliderField
            label="Dim amount"
            :value="settings.globalDimAmount"
            :min="0"
            :max="100"
            :step="1"
            :format="(value) => `${value}%`"
            @commit="emit('settings', { globalDimAmount: $event })"
          />
        </section>
      </div>
    </aside>
  </Transition>
</template>

<style scoped>
.drawer-enter-active,
.drawer-leave-active {
  transition: transform 180ms ease;
}
.drawer-enter-from,
.drawer-leave-to {
  transform: translateX(100%);
}
</style>

// fixtures/openslides/svelte/src/features/settings/SettingsDrawer.svelte
<script lang="ts">
  /** Right-side settings panel for project-level presentation options. */
  import { untrack } from "svelte";
  import { X } from "@lucide/svelte";
  import Button from "$lib/ui/Button.svelte";
  import ConfirmDialog from "$lib/ui/ConfirmDialog.svelte";
  import { type Project, type ThemeName } from "$lib/types";
  import {
    updateProjectSettingsMutation,
    updateProjectThemeMutation,
  } from "$lib/queries";
  import {
    clearPreviewProjectSetting,
    setEditorShowLineNumbers,
    setPreviewProjectSetting,
    setShowSlideHoverPreview,
  } from "$lib/stores/ui-state.svelte";
  import { previewProjectSettings } from "@/features/settings/preview-settings";
  import { loadDefaultProjectSettings } from "$lib/lib/backend-config-loader";
  import { supportedThemeOptions } from "$lib/lib/backend-config.svelte";
  import { cn } from "$lib/lib/utils";
  import { Z_INDEX } from "$lib/ui/Overlay.svelte";
  import {
    DEFAULT_GLOBAL_DIM_AMOUNT,
    DEFAULT_GLOBAL_SIZE_UP_AMOUNT,
    DEFAULT_THEME,
  } from "$lib/constants";
  import { escapeKey } from "$lib/actions/escape-key";
  import SettingsSection from "$lib/ui/SettingsSection.svelte";
  import GlobalAnimationSection from "@/features/settings/GlobalAnimationSection.svelte";
  import DrawerThemeSection from "./drawer/DrawerThemeSection.svelte";
  import DrawerCodeLayoutSection from "./drawer/DrawerCodeLayoutSection.svelte";
  import DrawerCodeBackgroundSection from "./drawer/DrawerCodeBackgroundSection.svelte";
  import DrawerPreviewSection from "./drawer/DrawerPreviewSection.svelte";
  import DrawerEditorSection from "./drawer/DrawerEditorSection.svelte";
  import DimColorPicker from "./DimColorPicker.svelte";
  import type { SettingsPatch } from "$lib/lib/tauri-api";
  import type {
    GlobalAnimationKey,
    PreviewProjectSettings,
  } from "$lib/stores/types";

  let {
    project,
    open,
    onClose,
  }: {
    project: Project;
    open: boolean;
    onClose: () => void;
  } = $props();

  type DrawerTab = "theme" | "layout" | "motion";

  const TABS: { id: DrawerTab; label: string }[] = [
    { id: "theme", label: "Theme" },
    { id: "layout", label: "Layout" },
    { id: "motion", label: "Motion" },
  ];

  const projectId = untrack(() => project.id);
  const updateSettings = updateProjectSettingsMutation(projectId);
  const updateTheme = updateProjectThemeMutation(projectId);

  let activeTab = $state<DrawerTab>("theme");
  let resetConfirmOpen = $state(false);
  let drawerEl: HTMLElement | null = $state(null);

  const previewProject = $derived(previewProjectSettings());

  $effect(() => {
    if (!open) {
      clearTransientPreviews();
      resetConfirmOpen = false;
    }
  });

  $effect(() => {
    if (!open) return;

    function handleDocumentPointerDown(event: PointerEvent) {
      if (resetConfirmOpen) return;
      const target = event.target;
      if (target instanceof Node && drawerEl?.contains(target)) return;
      onClose();
    }

    document.addEventListener("pointerdown", handleDocumentPointerDown, true);
    return () => {
      document.removeEventListener(
        "pointerdown",
        handleDocumentPointerDown,
        true,
      );
    };
  });

  const s = $derived(project.settings);
  const activeTabIndex = $derived(
    Math.max(
      0,
      TABS.findIndex((tab) => tab.id === activeTab),
    ),
  );

  const effTheme = $derived(previewProject.theme ?? project.theme);
  const defaultTheme = $derived(
    supportedThemeOptions()[0]?.value ?? DEFAULT_THEME,
  );
  const effFontSize = $derived(previewProject.fontSize ?? s.fontSize);
  const effLineHeight = $derived(previewProject.lineHeight ?? s.lineHeight);
  const effEditorFontSize = $derived(
    previewProject.editorFontSize ?? s.editorFontSize,
  );
  const effGlobalTransition = $derived(
    previewProject.globalTransitionDuration ?? s.globalTransitionDuration,
  );
  const effGlobalStagger = $derived(
    previewProject.globalStagger ?? s.globalStagger,
  );
  const effGlobalDimAmount = $derived(
    previewProject.globalDimAmount ??
      s.globalDimAmount ??
      DEFAULT_GLOBAL_DIM_AMOUNT,
  );
  const effGlobalSizeUpAmount = $derived(
    previewProject.globalSizeUpAmount ??
      s.globalSizeUpAmount ??
      DEFAULT_GLOBAL_SIZE_UP_AMOUNT,
  );
  const effHighlightDimColor = $derived(
    (previewProject.highlightDimColor ?? s.highlightDimColor ?? "theme") as
      "black" | "theme",
  );
  const globalMotionActive = $derived(
    s.useGlobalTransition || s.useGlobalStagger || s.useGlobalHighlight,
  );

  function patch(partial: SettingsPatch) {
    updateSettings.mutate(partial);
  }

  function previewGlobalSetting(
    key: GlobalAnimationKey,
    value: number | string,
  ) {
    const typedKey = key as keyof PreviewProjectSettings;
    setPreviewProjectSetting(
      typedKey,
      value as PreviewProjectSettings[typeof typedKey],
    );
  }

  function clearTransientPreviews() {
    clearPreviewProjectSetting("theme");
    clearPreviewProjectSetting("useBlackCodeBackground");
    clearPreviewProjectSetting("highlightDimColor");
    clearPreviewProjectSetting("fontSize");
    clearPreviewProjectSetting("lineHeight");
    clearPreviewProjectSetting("editorFontSize");
    clearPreviewProjectSetting("globalTransitionDuration");
    clearPreviewProjectSetting("globalStagger");
    clearPreviewProjectSetting("globalDimAmount");
    clearPreviewProjectSetting("globalSizeUpAmount");
  }

  function handlePreviewTheme(theme: ThemeName) {
    setPreviewProjectSetting("theme", theme);
  }

  function clearThemePreview() {
    clearPreviewProjectSetting("theme");
  }

  async function resetAllSettings() {
    clearTransientPreviews();
    const defaults = await loadDefaultProjectSettings();
    updateTheme.mutate(defaultTheme);
    if (defaults) {
      const {
        currentSlideId: _currentSlideId,
        language: _language,
        ...rest
      } = defaults;
      patch(rest as SettingsPatch);
      setEditorShowLineNumbers(defaults.showLineNumbers);
    }
    setShowSlideHoverPreview(false);
    resetConfirmOpen = false;
  }

  function handleEscape() {
    if (!open) return;
    if (resetConfirmOpen) {
      resetConfirmOpen = false;
      return;
    }
    onClose();
  }
</script>

<div
  class="pointer-events-none fixed inset-0"
  style="z-index: {Z_INDEX.drawer};"
  aria-hidden={!open}
>
  <div
    bind:this={drawerEl}
    class={cn(
      "pointer-events-auto absolute top-0 right-0 flex h-full w-[420px] flex-col overflow-hidden rounded-l-2xl border-l border-border/60 bg-background/95 shadow-[-8px_0_30px_rgba(0,0,0,0.12)] backdrop-blur-xl will-change-transform motion-safe:transition-transform motion-safe:duration-200 motion-safe:ease-out motion-reduce:transition-none",
      open ? "translate-x-0" : "translate-x-full",
    )}
    role="dialog"
    aria-modal="false"
    aria-label="Settings"
    use:escapeKey={{ onEscape: handleEscape, delayMs: 50 }}
  >
    <div class="flex h-12 shrink-0 items-center justify-between border-b px-4">
      <h2 class="truncate text-sm font-semibold">Settings</h2>
      <Button
        variant="ghost"
        size="icon"
        class="h-8 w-8 focus-visible:ring-offset-2 focus-visible:ring-offset-card"
        onclick={onClose}
        aria-label="Close settings"
      >
        <X class="h-4 w-4" />
      </Button>
    </div>

    <div class="shrink-0 border-b px-4 py-3">
      <div
        class="relative grid h-9 grid-cols-3 rounded-lg bg-muted p-1"
        role="tablist"
        aria-label="Settings categories"
      >
        <span
          class="absolute top-1 bottom-1 left-1 rounded-md bg-background shadow-sm motion-safe:transition-transform motion-safe:duration-200 motion-reduce:transition-none"
          style="width: calc((100% - 0.5rem) / 3); transform: translateX({activeTabIndex *
            100}%);"
          aria-hidden="true"
        ></span>
        {#each TABS as tab (tab.id)}
          {@const active = activeTab === tab.id}
          <button
            type="button"
            role="tab"
            aria-selected={active}
            aria-controls={`settings-panel-${tab.id}`}
            id={`settings-tab-${tab.id}`}
            class={cn(
              "relative z-10 rounded-md text-sm font-medium transition-colors focus-visible:ring-2 focus-visible:ring-primary/50 focus-visible:ring-offset-2 focus-visible:ring-offset-card focus-visible:outline-none",
              active
                ? "text-primary"
                : "text-muted-foreground hover:text-foreground",
            )}
            onclick={() => {
              activeTab = tab.id;
            }}
          >
            {tab.label}
          </button>
        {/each}
      </div>
    </div>

    <div
      id={`settings-panel-${activeTab}`}
      role="tabpanel"
      aria-labelledby={`settings-tab-${activeTab}`}
      class="min-h-0 flex-1 overflow-y-auto p-4"
    >
      <div class="space-y-5">
        {#if activeTab === "theme"}
          <DrawerThemeSection
            currentTheme={project.theme}
            onPreviewTheme={handlePreviewTheme}
            onClearPreviewTheme={clearThemePreview}
            onCommitTheme={(theme: ThemeName) => updateTheme.mutate(theme)}
          />

          <DrawerCodeBackgroundSection
            checked={s.useBlackCodeBackground}
            theme={effTheme}
            onChange={(v) => patch({ useBlackCodeBackground: v })}
          />

          <SettingsSection title="Highlight dim color">
            <DimColorPicker
              value={effHighlightDimColor}
              theme={effTheme}
              onPreview={(v) =>
                setPreviewProjectSetting("highlightDimColor", v)}
              onPreviewEnd={() =>
                clearPreviewProjectSetting("highlightDimColor")}
              onCommit={(v) => patch({ highlightDimColor: v })}
            />
          </SettingsSection>
        {:else if activeTab === "layout"}
          <DrawerCodeLayoutSection
            value={s.codeAlign ?? "left"}
            onChange={(align) => patch({ codeAlign: align })}
          />

          <DrawerPreviewSection
            settings={s}
            {effFontSize}
            {effLineHeight}
            onPatch={patch}
          />

          <DrawerEditorSection {effEditorFontSize} onPatch={patch} />
        {:else}
          <SettingsSection
            title="Global Animations"
            badge={globalMotionActive ? "GLOBAL" : undefined}
          >
            <GlobalAnimationSection
              settings={s}
              effTransition={effGlobalTransition}
              effStagger={effGlobalStagger}
              {effGlobalDimAmount}
              {effGlobalSizeUpAmount}
              onPreview={previewGlobalSetting}
              onCommit={patch}
            />
          </SettingsSection>
        {/if}

        <div class="pt-2">
          <button
            type="button"
            class="rounded px-1 py-1 text-xs font-medium text-muted-foreground transition-colors hover:text-foreground focus-visible:ring-2 focus-visible:ring-primary/50 focus-visible:ring-offset-2 focus-visible:ring-offset-card focus-visible:outline-none"
            onclick={() => {
              resetConfirmOpen = true;
            }}
          >
            Reset all settings
          </button>
        </div>
      </div>
    </div>
  </div>
</div>

<ConfirmDialog
  open={resetConfirmOpen}
  title="Reset presentation settings?"
  description="This restores theme, layout, typography, visibility, and motion settings to their defaults."
  confirmLabel="Reset"
  destructive={false}
  onConfirm={resetAllSettings}
  onCancel={() => {
    resetConfirmOpen = false;
  }}
/>
