// fixtures/hand-authored/svelte/src/components/notifications/NotificationList.svelte
<script>
  import { notifications as initial } from "@shared/catalog.js";
  let notices = $state(initial.map((item) => ({ ...item })));
  let unreadOnly = $state(false);
  let visible = $derived(unreadOnly ? notices.filter((item) => !item.read) : notices);
  function dismiss(id) { notices = notices.filter((item) => item.id !== id); }
</script>
<article class="panel stack">
  <div class="inline"><h3>Inbox</h3><label class="inline"><input bind:checked={unreadOnly} type="checkbox" /> Unread only</label></div>
  {#each visible as notice (notice.id)}<article><strong>{notice.title}</strong><small>{notice.channel}</small><button onclick={() => dismiss(notice.id)}>Dismiss</button></article>{/each}
  {#if !visible.length}<p>Nothing to review</p>{/if}
  <output data-testid="notice-count">{visible.length} notifications</output>
</article>

// fixtures/hand-authored/vue/src/components/notifications/NotificationList.vue
<script setup>
import { notifications as initial } from "@shared/catalog.js";
import { computed, ref } from "vue";
const notices = ref(initial.map((item) => ({ ...item })));
const unreadOnly = ref(false);
const visible = computed(() => unreadOnly.value ? notices.value.filter((item) => !item.read) : notices.value);
function dismiss(id) { notices.value = notices.value.filter((item) => item.id !== id); }
</script>
<template>
  <article class="panel stack">
    <div class="inline"><h3>Inbox</h3><label class="inline"><input v-model="unreadOnly" type="checkbox" /> Unread only</label></div>
    <article v-for="notice in visible" :key="notice.id"><strong>{{ notice.title }}</strong><small>{{ notice.channel }}</small><button @click="dismiss(notice.id)">Dismiss</button></article>
    <p v-if="!visible.length">Nothing to review</p>
    <output data-testid="notice-count">{{ visible.length }} notifications</output>
  </article>
</template>
