// fixtures/hand-authored/svelte/src/components/reader/AnnotationComposer.svelte
<script>
  let { section } = $props();
  let note = $state("");
  let kind = $state("observation");
  let saved = $state([]);
  let canSave = $derived(note.trim().length >= 4);
  function save() {
    if (!canSave) return;
    saved.push({ id: Date.now(), section, kind, text: note.trim() });
    note = "";
  }
</script>

<aside class="panel stack">
  <h3>Annotation</h3>
  <label>Kind <select bind:value={kind}><option>observation</option><option>question</option><option>citation</option></select></label>
  <label>Note <textarea bind:value={note} rows="4" data-testid="annotation-note"></textarea></label>
  <button disabled={!canSave} onclick={save}>Save annotation</button>
  <output data-testid="annotation-count">{saved.length} saved</output>
</aside>

// fixtures/hand-authored/vue/src/components/reader/AnnotationComposer.vue
<script setup>
import { computed, ref } from "vue";

const props = defineProps({ section: { type: String, required: true } });
const note = ref("");
const kind = ref("observation");
const saved = ref([]);
const canSave = computed(() => note.value.trim().length >= 4);
function save() {
  if (!canSave.value) return;
  saved.value.push({ id: Date.now(), section: props.section, kind: kind.value, text: note.value.trim() });
  note.value = "";
}
</script>

<template>
  <aside class="panel stack">
    <h3>Annotation</h3>
    <label>Kind <select v-model="kind"><option>observation</option><option>question</option><option>citation</option></select></label>
    <label>Note <textarea v-model="note" rows="4" data-testid="annotation-note" /></label>
    <button :disabled="!canSave" @click="save">Save annotation</button>
    <output data-testid="annotation-count">{{ saved.length }} saved</output>
  </aside>
</template>
