// fixtures/hand-authored/svelte/src/components/reader/ContentsTree.svelte
<script>
  import { readerSections } from "@shared/catalog.js";
  let { selected = $bindable() } = $props();
</script>

<nav class="panel stack" aria-label="Document contents">
  <h3>Contents</h3>
  {#each readerSections as section (section.id)}
    <button aria-current={selected === section.id ? "location" : undefined} onclick={() => (selected = section.id)}>
      {section.label} <small>{section.words} words</small>
    </button>
  {/each}
</nav>

// fixtures/hand-authored/vue/src/components/reader/ContentsTree.vue
<script setup>
import { readerSections } from "@shared/catalog.js";

const selected = defineModel({ type: String, required: true });
</script>

<template>
  <nav class="panel stack" aria-label="Document contents">
    <h3>Contents</h3>
    <button
      v-for="section in readerSections"
      :key="section.id"
      :aria-current="selected === section.id ? 'location' : undefined"
      @click="selected = section.id"
    >
      {{ section.label }} <small>{{ section.words }} words</small>
    </button>
  </nav>
</template>
