// fixtures/openslides/vue/src/features/dashboard/Dashboard.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from "vue";
import { useRouter } from "vue-router";
import { Command, FolderOpen, Plus, Upload } from "lucide-vue-next";
import {
  createProjectMutation,
  deleteProjectMutation,
  duplicateProjectMutation,
  exportProjectMutation,
  importProjectMutation,
  projectsQuery,
  renameProjectMutation,
  updateProjectThemeMutation,
} from "$lib/queries";
import { DEFAULT_THEME } from "$lib/constants";
import { setWindowTitle } from "$lib/lib/window-title";
import { setIsCommandOpen, setIsShortcutsOpen } from "$lib/stores/ui-state";
import Button from "$lib/ui/Button.vue";
import ConfirmDialog from "$lib/ui/ConfirmDialog.vue";
import EmptyState from "$lib/ui/EmptyState.vue";
import AsyncState from "$lib/components/AsyncState.vue";
import TitleBar from "$lib/components/TitleBar.vue";
import CreateDeckTile from "./CreateDeckTile.vue";
import ProjectGrid from "./ProjectGrid.vue";

const router = useRouter();
const listQuery = projectsQuery();
const createMutation = createProjectMutation();
const renameMutation = renameProjectMutation();
const duplicateMutation = duplicateProjectMutation();
const deleteMutation = deleteProjectMutation();
const exportMutation = exportProjectMutation();
const importMutation = importProjectMutation();
const projects = computed(() => listQuery.data.value ?? []);
const creating = ref(false);
const newName = ref("Untitled Presentation");
const selectedTheme = ref(DEFAULT_THEME);
const deleteTarget = ref<{ id: string; name: string } | null>(null);

async function createProject() {
  const project = await createMutation.mutateAsync(
    newName.value.trim() || "Untitled Presentation",
  );
  if (selectedTheme.value !== project.theme) {
    await updateProjectThemeMutation(project.id).mutateAsync(
      selectedTheme.value,
    );
  }
  creating.value = false;
  newName.value = "Untitled Presentation";
  await router.push({ name: "editor", params: { projectId: project.id } });
}

function keydown(event: KeyboardEvent) {
  if (event.key === "?" && !(event.target instanceof HTMLInputElement)) {
    event.preventDefault();
    setIsShortcutsOpen(true);
  }
}
function openCreate() {
  creating.value = true;
}

onMounted(() => {
  setWindowTitle("OpenSlides — Presentations");
  window.addEventListener("keydown", keydown);
  window.addEventListener("openslides:new-project", openCreate);
});
onBeforeUnmount(() => {
  window.removeEventListener("keydown", keydown);
  window.removeEventListener("openslides:new-project", openCreate);
});
</script>

<template>
  <div class="flex h-full flex-col bg-background">
    <TitleBar>
      <template #leading>
        <div class="flex items-center gap-2">
          <img
            src="/openslides-logo.svg"
            alt="OpenSlides"
            class="h-8 w-8 rounded-lg object-cover"
          />
          <span class="text-sm font-semibold">OpenSlides</span>
        </div>
      </template>
      <template #trailing>
        <Button
          variant="ghost"
          size="icon"
          title="Command palette"
          @click="setIsCommandOpen(true)"
        >
          <Command />
        </Button>
        <Button
          variant="outline"
          size="sm"
          :disabled="importMutation.isPending.value"
          @click="importMutation.mutate()"
        >
          <Upload />Import
        </Button>
        <Button size="sm" @click="creating = true">
          <Plus />New Presentation
        </Button>
      </template>
    </TitleBar>

    <div
      v-if="creating && !listQuery.isLoading.value"
      class="mx-auto w-full max-w-7xl px-6 pt-8"
    >
      <CreateDeckTile
        v-model:expanded="creating"
        v-model:name="newName"
        v-model:selected-theme="selectedTheme"
        :pending="createMutation.isPending.value"
        standalone
        @create="createProject"
      />
    </div>

    <AsyncState
      :is-loading="listQuery.isLoading.value"
      :is-error="listQuery.isError.value"
      :error="(listQuery.error.value as Error | null)"
      loading-label="Loading presentations…"
    >
      <div
        v-if="projects.length"
        class="flex min-h-0 flex-1"
      >
        <ProjectGrid
          :projects="projects"
          @open="router.push({ name: 'editor', params: { projectId: $event } })"
          @rename="
            (id, name) =>
              renameMutation.mutate({ projectId: id, name })
          "
          @duplicate="duplicateMutation.mutate"
          @export="exportMutation.mutate"
          @remove="
            (id, name) => (deleteTarget = { id, name })
          "
        />
      </div>
      <EmptyState
        v-else-if="!creating"
        :icon="FolderOpen"
        title="No presentations yet"
        description="Create your first presentation, or import an existing one."
      >
        <Button @click="creating = true"><Plus />Create Presentation</Button>
        <Button variant="outline" @click="importMutation.mutate()">
          <Upload />Import
        </Button>
      </EmptyState>
    </AsyncState>

    <ConfirmDialog
      :open="deleteTarget !== null"
      :title="`Delete &quot;${deleteTarget?.name ?? ''}&quot;?`"
      description="This cannot be undone."
      @confirm="
        deleteTarget &&
          deleteMutation.mutate(deleteTarget.id, {
            onSettled: () => (deleteTarget = null),
          })
      "
      @cancel="deleteTarget = null"
    />
  </div>
</template>

// fixtures/openslides/svelte/src/features/dashboard/Dashboard.svelte
<script lang="ts">
  /** Project dashboard orchestrator. */
  import { Command as CommandIcon, Plus, Upload } from "@lucide/svelte";
  import Button from "$lib/ui/Button.svelte";
  import TitleBar from "$lib/components/TitleBar.svelte";
  import CommandPalette from "$lib/components/CommandPalette.svelte";
  import ShortcutsHelp from "$lib/components/ShortcutsHelp.svelte";
  import CreateDeckTile from "@/features/dashboard/CreateDeckTile.svelte";
  import DashboardStates from "@/features/dashboard/DashboardStates.svelte";
  import ProjectGrid from "@/features/dashboard/ProjectGrid.svelte";
  import ConfirmDialog from "$lib/ui/ConfirmDialog.svelte";
  import { createRenameState } from "$lib/lib/rename-state.svelte";
  import { isModKey, isTypingTarget } from "$lib/lib/keyboard";
  import { modKeyLabel } from "$lib/lib/platform";
  import { setWindowTitle } from "$lib/lib/window-title";
  import {
    ui,
    applyUiTheme,
    setIsCommandOpen,
    setIsShortcutsOpen,
  } from "$lib/stores/ui-state.svelte";
  import { createDashboardState } from "./dashboard-state.svelte";
  import {
    createDashboardActions,
    installDashboardMenu,
  } from "./dashboard-actions";
  import { provideProjectCardActions } from "./project-card-actions.svelte";

  const st = createDashboardState();
  const listQuery = st.query;
  const projects = $derived(st.projects);
  const actions = createDashboardActions(st);

  // Native + document window title for the dashboard route.
  $effect(() => {
    setWindowTitle("OpenSlides — Presentations");
  });

  $effect(() => {
    applyUiTheme(ui.isDarkUi);
  });

  $effect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "?" && !isTypingTarget(e.target) && !isModKey(e)) {
        e.preventDefault();
        setIsShortcutsOpen(true);
      }
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  });

  const rename = createRenameState(async (id: string, name: string) => {
    await actions.renameMutation.mutateAsync({
      projectId: id,
      name: name || "Untitled Presentation",
    });
  });

  // Card actions live in context so ProjectCard consumers (grid cells, fan
  // overlay, drag clone) don't thread a dozen callbacks through each level.
  provideProjectCardActions({
    get renamingId() {
      return rename.renamingId;
    },
    get renameValue() {
      return rename.value;
    },
    get duplicateBusy() {
      return actions.duplicateMutation.isPending;
    },
    get commitBusy() {
      return actions.renameMutation.isPending;
    },
    setRenameValue: (v: string) => (rename.value = v),
    commitRename: rename.commit,
    cancelRename: rename.cancel,
    startRename: rename.start,
    open: actions.open,
    duplicate: actions.duplicate,
    exportProject: actions.exportProject,
    remove: actions.requestDelete,
  });

  installDashboardMenu(st, actions);

  const mod = modKeyLabel();
</script>

<div class="flex h-full flex-col bg-background">
  <TitleBar>
    {#snippet leading()}
      <div class="flex items-center gap-2">
        <img
          src="/openslides-logo.svg"
          alt="OpenSlides"
          class="h-8 w-8 rounded-lg object-cover"
        />
        <span class="text-sm font-semibold">OpenSlides</span>
      </div>
    {/snippet}
    {#snippet trailing()}
      <Button
        variant="ghost"
        size="icon"
        class="h-8 w-8"
        title="Command palette ({mod}K)"
        onclick={() => setIsCommandOpen(true)}
      >
        <CommandIcon class="h-3.5 w-3.5" />
      </Button>
      <Button
        variant="outline"
        size="sm"
        class="gap-1.5"
        onclick={() => void actions.importProject()}
        disabled={actions.importMutation.isPending}
      >
        <Upload class="h-4 w-4" />Import
      </Button>
      <Button onclick={() => (st.creating = true)} class="gap-2" size="sm">
        <Plus class="h-4 w-4" />New Presentation
      </Button>
    {/snippet}
  </TitleBar>

  {#if st.creating && !listQuery.isLoading && !listQuery.isError}
    <div class="mx-auto max-w-7xl px-6 pt-8">
      <CreateDeckTile
        isExpanded={st.creating || projects.length === 0}
        onToggleExpand={(expanded) => (st.creating = expanded)}
        name={st.newName}
        onNameChange={(v) => (st.newName = v)}
        selectedTheme={st.selectedTheme}
        onThemeChange={(t) => (st.selectedTheme = t)}
        onCreate={() => void actions.create()}
        isPending={actions.createMutation.isPending}
        isStandalone={true}
      />
    </div>
  {/if}

  <DashboardStates
    isLoading={listQuery.isLoading}
    isError={listQuery.isError}
    error={(listQuery.error as Error | null) ?? null}
    projectCount={projects.length}
    onCreate={() => (st.creating = true)}
    onImport={() => void actions.importProject()}
    showEmptyState={!st.creating}
  >
    {#if !listQuery.isLoading && !listQuery.isError && projects.length > 0}
      <ProjectGrid {projects} />
    {/if}
  </DashboardStates>

  <CommandPalette />
  <ShortcutsHelp />
  <ConfirmDialog
    open={st.deleteTarget !== null}
    title="Delete &quot;{st.deleteTarget?.name}&quot;?"
    description="This cannot be undone."
    confirmLabel="Delete"
    destructive
    onConfirm={actions.confirmDelete}
    onCancel={() => (st.deleteTarget = null)}
  />
</div>
