// fixtures/openslides/vue/src/features/dashboard/ProjectThumb.vue
<script setup lang="ts">
import { computed } from "vue";
import { FileCode } from "lucide-vue-next";
import type { ProjectSummary } from "$lib/types";
import CodeThumbnail from "$lib/ui/CodeThumbnail.vue";
import { useShikiHtml } from "$lib/shiki/use-shiki-html";

const props = withDefaults(
  defineProps<{
    project: ProjectSummary;
    fontSize?: number;
    class?: string;
    codeClassName?: string;
  }>(),
  { fontSize: 5.5, class: undefined, codeClassName: undefined },
);

const html = useShikiHtml({
  code: computed(() => props.project.firstSlideCode),
  language: computed(() => props.project.language),
  theme: computed(() => props.project.theme),
});
</script>

<template>
  <CodeThumbnail
    :html="project.firstSlideThumbnail || html"
    :theme="project.theme"
    :font-size="fontSize"
    :class="$props.class"
    :code-class-name="codeClassName"
  >
    <template #fallback>
      <FileCode class="h-5 w-5 text-primary" />
    </template>
  </CodeThumbnail>
</template>

// fixtures/openslides/svelte/src/features/dashboard/ProjectThumb.svelte
<script lang="ts">
  import { FileCode } from "@lucide/svelte";
  import { createSlideThumbnail } from "$lib/shiki/slide-thumbnail.svelte";
  import { type ProjectSummary } from "$lib/types";
  import CodeThumbnail from "$lib/ui/CodeThumbnail.svelte";
  import { cn } from "$lib/lib/utils";

  let {
    project,
    class: className,
    codeClassName,
    fontSize = 5.5,
  }: {
    project: ProjectSummary;
    class?: string;
    codeClassName?: string;
    fontSize?: number;
  } = $props();

  const thumb = createSlideThumbnail(() => ({
    slideId: project.firstSlideId || project.id,
    code: project.firstSlideCode,
    theme: project.theme,
    language: project.language,
    initialHtml: project.firstSlideThumbnail || undefined,
  }));
</script>

<CodeThumbnail
  bind:ref={thumb.el}
  html={thumb.html}
  theme={project.theme}
  {fontSize}
  lineHeight={1.3}
  class={cn("relative w-full overflow-hidden", className)}
  {codeClassName}
>
  {#snippet fallback()}
    <FileCode class="h-5 w-5 text-primary" />
  {/snippet}
</CodeThumbnail>
