// fixtures/openslides/svelte/src/features/slides/SlideSearchDialog.svelte
<script lang="ts" module>
  export type SearchScope = "slides" | "code";
</script>

<script lang="ts">
  /** Centered find control that leaves the workspace visible behind it. */
  import { Search } from "@lucide/svelte";
  import { fade } from "svelte/transition";
  import { Z_INDEX } from "$lib/ui/Overlay.svelte";
  import { modKeyLabel } from "$lib/lib/platform";
  import { rise } from "$lib/ui/transitions/rise";
  import { EASE_DIM } from "$lib/lib/easings";
  import { focusTrap } from "$lib/actions/focus-trap";

  let {
    open,
    query,
    scope,
    onQueryChange,
    onScopeChange,
    onSubmitCodeSearch,
    onClose,
  }: {
    open: boolean;
    query: string;
    scope: SearchScope;
    onQueryChange: (value: string) => void;
    onScopeChange: (scope: SearchScope) => void;
    onSubmitCodeSearch: () => void;
    onClose: () => void;
  } = $props();

  let inputEl = $state<HTMLInputElement | null>(null);

  $effect(() => {
    if (!open) return;
    const raf = requestAnimationFrame(() => inputEl?.focus());
    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key === "Escape") onClose();
      if (event.key === "Enter" && scope === "code") onSubmitCodeSearch();
    };
    window.addEventListener("keydown", onKeyDown);
    return () => {
      cancelAnimationFrame(raf);
      window.removeEventListener("keydown", onKeyDown);
    };
  });
</script>

{#if open}
  <div
    class="fixed inset-0 flex items-center justify-center p-4"
    style="z-index: {Z_INDEX.command};"
    transition:fade={{ duration: 150, easing: EASE_DIM }}
  >
    <button
      type="button"
      class="absolute inset-0 cursor-default"
      aria-label="Close search"
      onclick={onClose}
    ></button>
    <div
      use:focusTrap
      class="relative w-full max-w-lg overflow-hidden rounded-xl border bg-card shadow-2xl"
      transition:rise={{ duration: 150, dy: 8, from: 0.98 }}
      role="dialog"
      aria-modal="true"
      aria-label="Search slides"
    >
      <div class="flex items-center gap-2 border-b px-4 py-3">
        <Search class="h-4 w-4 text-muted-foreground" />
        <input
          bind:this={inputEl}
          value={query}
          oninput={(event) => onQueryChange(event.currentTarget.value)}
          placeholder={scope === "slides"
            ? "Find slides by name or code…"
            : "Find in the current editor…"}
          aria-label={scope === "slides"
            ? "Find slides by name or code"
            : "Find in the current editor"}
          class="min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-muted-foreground"
        />
        <span class="text-[10px] text-muted-foreground">{modKeyLabel()}F</span>
      </div>
      <div class="flex items-center gap-2 px-4 py-3 text-xs">
        <span class="mr-1 text-muted-foreground">Search</span>
        <label
          class="flex cursor-pointer items-center gap-2 rounded-md px-2 py-1.5 hover:bg-muted"
        >
          <input
            type="radio"
            name="search-scope"
            checked={scope === "slides"}
            onchange={() => onScopeChange("slides")}
          />
          Slides
        </label>
        <label
          class="flex cursor-pointer items-center gap-2 rounded-md px-2 py-1.5 hover:bg-muted"
        >
          <input
            type="radio"
            name="search-scope"
            checked={scope === "code"}
            onchange={() => onScopeChange("code")}
          />
          Code editor
        </label>
        <span class="ml-auto text-[10px] text-muted-foreground">
          {scope === "code" ? "Enter to find" : "Results update below"}
        </span>
      </div>
    </div>
  </div>
{/if}

// fixtures/openslides/vue/src/features/slides/SlideSearchDialog.vue
<script setup lang="ts">
import { computed, nextTick, ref, watch } from "vue";
import { Search } from "lucide-vue-next";
import type { Project } from "$lib/types";
import { slideDisplayName } from "$lib/types";
import Overlay, { Z_INDEX } from "$lib/ui/Overlay.vue";

const props = defineProps<{ open: boolean; project: Project }>();
const emit = defineEmits<{ close: []; select: [id: string] }>();
const query = ref("");
const input = ref<HTMLInputElement | null>(null);
const matches = computed(() => {
  const needle = query.value.trim().toLowerCase();
  if (!needle) return props.project.slides;
  return props.project.slides.filter(
    (slide, index) =>
      slideDisplayName(slide, index).toLowerCase().includes(needle) ||
      slide.code.toLowerCase().includes(needle),
  );
});

watch(
  () => props.open,
  async (open) => {
    if (!open) return;
    query.value = "";
    await nextTick();
    input.value?.focus();
  },
);

function select(id: string) {
  emit("select", id);
  emit("close");
}
</script>

<template>
  <Overlay
    v-if="open"
    :z="Z_INDEX.command"
    placement="top"
    close-on-esc
    class="w-full max-w-xl"
    @close="emit('close')"
  >
    <div class="overflow-hidden rounded-xl border bg-card shadow-2xl">
      <div class="flex items-center gap-3 border-b px-4">
        <Search class="h-4 w-4 text-muted-foreground" />
        <input
          ref="input"
          v-model="query"
          class="h-12 min-w-0 flex-1 bg-transparent text-sm outline-none"
          placeholder="Search slide names and code…"
          @keydown.enter="matches[0] && select(matches[0].id)"
        />
      </div>
      <div class="max-h-[420px] overflow-y-auto p-2">
        <button
          v-for="slide in matches"
          :key="slide.id"
          class="block w-full rounded-md px-3 py-2 text-left hover:bg-accent"
          @click="select(slide.id)"
        >
          <span class="block text-sm font-medium">
            {{ slideDisplayName(slide, project.slides.indexOf(slide)) }}
          </span>
          <span class="block truncate font-mono text-[10px] text-muted-foreground">
            {{ slide.code.split("\n")[0] || "Empty slide" }}
          </span>
        </button>
        <p
          v-if="matches.length === 0"
          class="p-8 text-center text-sm text-muted-foreground"
        >
          No slides match “{{ query }}”
        </p>
      </div>
    </div>
  </Overlay>
</template>
