// fixtures/hand-authored/svelte/src/components/library/ImportQueue.svelte
<script>
  let jobs = $state([{ id: 1, file: "archive-a.pdf", completed: 82, status: "running" }, { id: 2, file: "notes.docx", completed: 100, status: "complete" }, { id: 3, file: "scan.pdf", completed: 0, status: "failed" }]);
  let active = $derived(jobs.filter((job) => job.status === "running").length);
  function retry(job) { job.status = "running"; job.completed = 1; }
</script>
<aside class="panel stack">
  <h3>Import queue</h3>
  {#each jobs as job (job.id)}<article><strong>{job.file}</strong><progress value={job.completed} max="100"></progress>{#if job.status === "failed"}<button onclick={() => retry(job)}>Retry</button>{/if}</article>{/each}
  <output data-testid="active-imports">{active} active imports</output>
</aside>

// fixtures/hand-authored/vue/src/components/library/ImportQueue.vue
<script setup>
import { computed, ref } from "vue";
const jobs = ref([{ id: 1, file: "archive-a.pdf", completed: 82, status: "running" }, { id: 2, file: "notes.docx", completed: 100, status: "complete" }, { id: 3, file: "scan.pdf", completed: 0, status: "failed" }]);
const active = computed(() => jobs.value.filter((job) => job.status === "running").length);
function retry(job) { job.status = "running"; job.completed = 1; }
</script>
<template>
  <aside class="panel stack">
    <h3>Import queue</h3>
    <article v-for="job in jobs" :key="job.id"><strong>{{ job.file }}</strong><progress :value="job.completed" max="100" /><button v-if="job.status === 'failed'" @click="retry(job)">Retry</button></article>
    <output data-testid="active-imports">{{ active }} active imports</output>
  </aside>
</template>
