// fixtures/openslides/vue/src/shared/components/TitleBar.vue
<script setup lang="ts">
import { cn } from "$lib/lib/utils";

withDefaults(
  defineProps<{
    title?: string;
    borderless?: boolean;
    class?: string;
  }>(),
  { title: undefined, borderless: false, class: undefined },
);
</script>

<template>
  <div
    :class="
      cn(
        'flex h-11 shrink-0 items-center justify-between gap-3 bg-card/70 px-3 backdrop-blur-md',
        !borderless && 'border-b border-border/60',
        $props.class,
      )
    "
  >
    <div class="flex min-w-0 items-center gap-2">
      <slot name="leading" />
      <span
        v-if="title"
        class="truncate text-sm font-medium text-foreground/90"
      >
        {{ title }}
      </span>
    </div>
    <div class="flex shrink-0 items-center gap-1">
      <slot name="trailing" />
    </div>
  </div>
</template>

// fixtures/openslides/svelte/src/shared/components/TitleBar.svelte
<script lang="ts">
  /**
   * In-app toolbar strip. Window chrome (traffic lights / caption buttons)
   * is handled by the OS via native decorations — no custom window controls.
   */
  import type { Snippet } from "svelte";
  import { cn } from "$lib/lib/utils";

  let {
    title,
    class: className,
    leading,
    trailing,
    borderless,
  }: {
    title?: string;
    class?: string;
    leading?: Snippet;
    trailing?: Snippet;
    /** When true, omit the bottom border (merged into a single bar). */
    borderless?: boolean;
  } = $props();
</script>

<div
  class={cn(
    "flex h-11 shrink-0 items-center justify-between gap-3 bg-card/70 px-3 backdrop-blur-md",
    !borderless && "border-b border-border/60",
    className,
  )}
>
  <div class="flex min-w-0 items-center gap-2">
    {@render leading?.()}
    {#if title}
      <span class="truncate text-sm font-medium text-foreground/90"
        >{title}</span
      >
    {/if}
  </div>
  <div class="flex shrink-0 items-center gap-1">{@render trailing?.()}</div>
</div>
