// fixtures/hand-authored/vue/src/routes/DashboardRoute.vue
<script setup>
import MetricBoard from "../components/dashboard/MetricBoard.vue";
import ActivityTimeline from "../components/dashboard/ActivityTimeline.vue";
import HealthChecklist from "../components/dashboard/HealthChecklist.vue";
</script>

<template>
  <section class="feature-route" data-testid="view-dashboard">
    <header>
      <p class="muted">Workspace overview</p>
      <h2>Dashboard</h2>
    </header>
    <div class="feature-grid">
      <MetricBoard />
      <ActivityTimeline />
      <HealthChecklist />
    </div>
  </section>
</template>

// fixtures/hand-authored/svelte/src/routes/DashboardRoute.svelte
<script>
  import MetricBoard from "../components/dashboard/MetricBoard.svelte";
  import ActivityTimeline from "../components/dashboard/ActivityTimeline.svelte";
  import HealthChecklist from "../components/dashboard/HealthChecklist.svelte";
</script>

<section class="feature-route" data-testid="view-dashboard">
  <header>
    <p class="muted">Workspace overview</p>
    <h2>Dashboard</h2>
  </header>
  <div class="feature-grid">
    <MetricBoard />
    <ActivityTimeline />
    <HealthChecklist />
  </div>
</section>
