// fixtures/hand-authored/svelte/src/routes/SettingsRoute.svelte
<script>
  import ProfileForm from "../components/settings/ProfileForm.svelte";
  import ShortcutEditor from "../components/settings/ShortcutEditor.svelte";
  import ThemeChooser from "../components/settings/ThemeChooser.svelte";
</script>
<section class="feature-route" data-testid="view-settings">
  <header><p class="muted">Personalize the workspace</p><h2>Settings</h2></header>
  <div class="feature-grid"><ProfileForm /><ThemeChooser /><ShortcutEditor /></div>
</section>

// fixtures/hand-authored/vue/src/routes/SettingsRoute.vue
<script setup>
import ProfileForm from "../components/settings/ProfileForm.vue";
import ShortcutEditor from "../components/settings/ShortcutEditor.vue";
import ThemeChooser from "../components/settings/ThemeChooser.vue";
</script>
<template>
  <section class="feature-route" data-testid="view-settings">
    <header><p class="muted">Personalize the workspace</p><h2>Settings</h2></header>
    <div class="feature-grid"><ProfileForm /><ThemeChooser /><ShortcutEditor /></div>
  </section>
</template>
