// fixtures/hand-authored/vue/src/components/editor/AutosaveStatus.vue
<script setup>
import { computed, ref } from "vue";
const props = defineProps({ body: { type: String, required: true } });
const savedBody = ref(props.body);
const revision = ref(1);
const dirty = computed(() => props.body !== savedBody.value);
function save() { savedBody.value = props.body; revision.value++; }
</script>
<template>
  <aside class="panel stack">
    <h3>Save status</h3>
    <p :class="{ muted: !dirty }">{{ dirty ? "Unsaved changes" : "All changes saved" }}</p>
    <button :disabled="!dirty" @click="save">Save revision</button>
    <output>Revision {{ revision }}</output>
  </aside>
</template>

// fixtures/hand-authored/svelte/src/components/editor/AutosaveStatus.svelte
<script>
  let { body } = $props();
  let savedBody = $state("Bundle size is an application property.");
  let revision = $state(1);
  let dirty = $derived(body !== savedBody);
  function save() { savedBody = body; revision++; }
</script>
<aside class="panel stack">
  <h3>Save status</h3>
  <p class:muted={!dirty}>{dirty ? "Unsaved changes" : "All changes saved"}</p>
  <button disabled={!dirty} onclick={save}>Save revision</button>
  <output>Revision {revision}</output>
</aside>
