// fixtures/openslides/vue/src/shared/ui/InlineEditableText.vue
<script setup lang="ts">
import { nextTick, onMounted, ref } from "vue";
import { Check, X } from "lucide-vue-next";
import { cn } from "$lib/lib/utils";
import Button from "./Button.vue";

const props = withDefaults(
  defineProps<{
    modelValue: string;
    withButtons?: boolean;
    commitBusy?: boolean;
    class?: string;
    buttonSize?: "sm" | "md";
    stopPropagation?: boolean;
    label?: string;
  }>(),
  {
    withButtons: false,
    commitBusy: false,
    class: undefined,
    buttonSize: "md",
    stopPropagation: true,
    label: "Edit name",
  },
);
const emit = defineEmits<{
  "update:modelValue": [value: string];
  commit: [];
  cancel: [];
}>();
const input = ref<HTMLInputElement | null>(null);

onMounted(async () => {
  await nextTick();
  input.value?.focus();
  input.value?.select();
});

function onKeydown(event: KeyboardEvent) {
  if (props.stopPropagation) event.stopPropagation();
  if (event.key === "Enter") emit("commit");
  if (event.key === "Escape") emit("cancel");
}
</script>

<template>
  <div
    :class="withButtons ? 'flex items-center gap-1' : undefined"
    @click="stopPropagation && $event.stopPropagation()"
  >
    <input
      ref="input"
      :aria-label="label"
      :class="
        cn(
          'select-text rounded-md border border-input bg-background px-2 text-sm outline-none focus:ring-1 focus:ring-ring',
          withButtons ? 'h-8 min-w-0 flex-1' : 'h-7 w-full',
          $props.class,
        )
      "
      :value="modelValue"
      @input="
        emit(
          'update:modelValue',
          ($event.currentTarget as HTMLInputElement).value,
        )
      "
      @blur="emit('commit')"
      @keydown="onKeydown"
    />
    <template v-if="withButtons">
      <Button
        variant="ghost"
        size="icon"
        :class="
          cn(
            'shrink-0',
            buttonSize === 'sm' && 'h-5 w-5 [&_svg]:size-3',
            buttonSize === 'md' && 'h-8 w-8',
          )
        "
        :disabled="commitBusy"
        @mousedown.prevent
        @click="emit('commit')"
      >
        <Check class="text-emerald-500" />
      </Button>
      <Button
        variant="ghost"
        size="icon"
        :class="
          cn(
            'shrink-0',
            buttonSize === 'sm' && 'h-5 w-5 [&_svg]:size-3',
            buttonSize === 'md' && 'h-8 w-8',
          )
        "
        @mousedown.prevent
        @click="emit('cancel')"
      >
        <X />
      </Button>
    </template>
  </div>
</template>

// fixtures/openslides/svelte/src/shared/ui/InlineEditableText.svelte
<script lang="ts">
  import { autofocus } from "$lib/actions/autofocus";
  import { Check, X } from "@lucide/svelte";
  import { cn } from "$lib/lib/utils";
  import Button from "./Button.svelte";

  let {
    value,
    onChange,
    onCommit,
    onCancel,
    withButtons = false,
    commitBusy = false,
    class: className,
    buttonSize = "md",
    stopPropagation = true,
    label = "Edit name",
  }: {
    value: string;
    onChange: (value: string) => void;
    onCommit: () => void;
    onCancel: () => void;
    /** ProjectCard style: show Check + X buttons next to the input */
    withButtons?: boolean;
    /** Disables the confirm button when withButtons is true */
    commitBusy?: boolean;
    /** Input classes */
    class?: string;
    /** Button sizing when withButtons is true */
    buttonSize?: "sm" | "md";
    /**
     * Whether click events on the rename area stop propagation.
     * Default true — rename clicks must not select the parent card.
     */
    stopPropagation?: boolean;
    /** Accessible name for the input (it renders no visible label). */
    label?: string;
  } = $props();

  // select-text overrides select-none ancestors (project cards became
  // unselectable so drag-to-stack can't highlight their labels).
  const inputClass =
    "select-text rounded-md border border-input bg-background px-2 text-sm outline-none focus:ring-1 focus:ring-ring";
</script>

{#snippet inputSnippet()}
  <input
    use:autofocus
    aria-label={label}
    class={cn(
      inputClass,
      withButtons ? "h-8 min-w-0 flex-1" : "h-7 w-full",
      className,
    )}
    {value}
    oninput={(e) => onChange(e.currentTarget.value)}
    onclick={(e) => stopPropagation && e.stopPropagation()}
    onblur={onCommit}
    onkeydown={(e) => {
      if (stopPropagation) e.stopPropagation();
      if (e.key === "Enter") onCommit();
      if (e.key === "Escape") onCancel();
    }}
  />
{/snippet}

{#if withButtons}
  <div
    class="flex items-center gap-1"
    onclick={(e) => stopPropagation && e.stopPropagation()}
    role="presentation"
  >
    {@render inputSnippet()}
    <Button
      variant="ghost"
      size="icon"
      class={cn(
        "shrink-0",
        buttonSize === "sm" && "h-5 w-5 [&_svg]:size-3",
        buttonSize === "md" && "h-8 w-8",
      )}
      onmousedown={(event) => event.preventDefault()}
      onclick={onCommit}
      disabled={commitBusy}
    >
      <Check class="text-emerald-500" />
    </Button>
    <Button
      variant="ghost"
      size="icon"
      class={cn(
        "shrink-0",
        buttonSize === "sm" && "h-5 w-5 [&_svg]:size-3",
        buttonSize === "md" && "h-8 w-8",
      )}
      onmousedown={(event) => event.preventDefault()}
      onclick={onCancel}
    >
      <X />
    </Button>
  </div>
{:else}
  {@render inputSnippet()}
{/if}
