// fixtures/hand-authored/vue/src/components/search/SearchResults.vue
<script setup>
import { searchRecords } from "@shared/catalog.js";
import { computed } from "vue";

const props = defineProps({
  query: { type: String, required: true },
  selectedTypes: { type: Array, required: true },
});
const matches = computed(() => {
  const needle = props.query.trim().toLowerCase();
  return searchRecords
    .filter((record) => !needle || record.title.toLowerCase().includes(needle))
    .filter((record) => !props.selectedTypes.length || props.selectedTypes.includes(record.type))
    .toSorted((left, right) => right.score - left.score);
});
</script>

<template>
  <section class="panel stack">
    <h3>{{ matches.length }} results</h3>
    <article v-for="record in matches" :key="record.id">
      <p><strong>{{ record.title }}</strong> <span class="muted">{{ record.type }}</span></p>
      <progress :value="record.score" max="1">{{ record.score }}</progress>
    </article>
    <p v-if="!matches.length" data-testid="empty-results">No matching records</p>
  </section>
</template>

// fixtures/hand-authored/svelte/src/components/search/SearchResults.svelte
<script>
  import { searchRecords } from "@shared/catalog.js";

  let { query, selectedTypes } = $props();
  let matches = $derived(
    searchRecords
      .filter((record) => !query.trim() || record.title.toLowerCase().includes(query.trim().toLowerCase()))
      .filter((record) => !selectedTypes.length || selectedTypes.includes(record.type))
      .toSorted((left, right) => right.score - left.score),
  );
</script>

<section class="panel stack">
  <h3>{matches.length} results</h3>
  {#each matches as record (record.id)}
    <article>
      <p><strong>{record.title}</strong> <span class="muted">{record.type}</span></p>
      <progress value={record.score} max="1">{record.score}</progress>
    </article>
  {/each}
  {#if !matches.length}<p data-testid="empty-results">No matching records</p>{/if}
</section>
