// fixtures/hand-authored/vue/src/components/notifications/QuietHours.vue
<script setup>
import { computed, ref } from "vue";
const enabled = ref(true);
const start = ref("21:00");
const end = ref("07:00");
const summary = computed(() => enabled.value ? `Muted from ${start.value} until ${end.value}` : "Notifications always allowed");
</script>
<template>
  <form class="panel stack">
    <h3>Quiet hours</h3>
    <label class="inline"><input v-model="enabled" type="checkbox" /> Enable schedule</label>
    <label>Start <input v-model="start" type="time" :disabled="!enabled" /></label>
    <label>End <input v-model="end" type="time" :disabled="!enabled" /></label>
    <output data-testid="quiet-summary">{{ summary }}</output>
  </form>
</template>

// fixtures/hand-authored/svelte/src/components/notifications/QuietHours.svelte
<script>
  let enabled = $state(true);
  let start = $state("21:00");
  let end = $state("07:00");
  let summary = $derived(enabled ? `Muted from ${start} until ${end}` : "Notifications always allowed");
</script>
<form class="panel stack">
  <h3>Quiet hours</h3>
  <label class="inline"><input bind:checked={enabled} type="checkbox" /> Enable schedule</label>
  <label>Start <input bind:value={start} type="time" disabled={!enabled} /></label>
  <label>End <input bind:value={end} type="time" disabled={!enabled} /></label>
  <output data-testid="quiet-summary">{summary}</output>
</form>
