// fixtures/weather-staged/vue/src/components/SearchForm.vue
<script setup>
import { locationLabel } from "@shared/weather-model.js";

defineProps({
  matches: { type: Array, required: true },
});

const model = defineModel({ type: String, required: true });
const emit = defineEmits(["select"]);
</script>

<template>
  <div class="search-panel">
    <div class="search-row">
      <label for="location-search">Location</label>
      <input
        id="location-search"
        v-model="model"
        type="search"
        autocomplete="off"
        placeholder="Search a city"
      />
    </div>
    <ul v-if="matches.length" class="suggestions" aria-label="Locations">
      <li v-for="location in matches" :key="location.id">
        <button type="button" @click="emit('select', location)">
          <strong>{{ locationLabel(location) }}</strong>
          <span class="muted"> — {{ location.country }}</span>
        </button>
      </li>
    </ul>
  </div>
</template>

// fixtures/weather-staged/svelte/src/components/SearchForm.svelte
<script>
  import { locationLabel } from "@shared/weather-model.js";

  let { query = $bindable(), matches, onselect } = $props();
</script>

<div class="search-panel">
  <div class="search-row">
    <label for="location-search">Location</label>
    <input
      id="location-search"
      bind:value={query}
      type="search"
      autocomplete="off"
      placeholder="Search a city"
    />
  </div>
  {#if matches.length}
    <ul class="suggestions" aria-label="Locations">
      {#each matches as location (location.id)}
        <li>
          <button type="button" onclick={() => onselect(location)}>
            <strong>{locationLabel(location)}</strong>
            <span class="muted"> — {location.country}</span>
          </button>
        </li>
      {/each}
    </ul>
  {/if}
</div>
